### ISSUE TITLE
toFile()

### ISSUE THREAD

**Issue by yzh1255245824** [huan/file-box#77]
Can the file obtained by `message.tofilebox()` be extracted according to the name of the file itself? 

According to the description in the introduction, `tofile()` seems to have to manually specify the name of the file so that the file suffix can be generated?

**Comment by huan** [comment]
Cloud you please provide a sample code to demonstrate what problem you are facing and want to resolve?

**Comment by yzh1255245824** [comment]
For example，I send a image called `pic.jpg` to the chatbot on the wechat. Then I use `file-box` to receive it like this:
```javascript
const fileBox = await msg.toFileBox();
await fileBox.toFile();
```
As you know, this will create a JPG file in the root project path. But the file name is `message-xxxx.jpg`, not the `pic.jpg`.

---

I also know that if specify the file path, it will create a file with the specified name in the specific path. Like this:
```javascript
const fileName = `${moment().format("X")}.jpg`; //! unix时间戳做文件名
const filePath = path.join(__dirname, `../../picture-bed/uploads/${fileName}`); //! 绝对路径,存入图床
await fileBox.toFile(filePath);
```
This will get a `1644378546.jpg` file in the `/uploads`. But it also raises another problem: 
> How can I confirm the format of the picture sent by the other party.

---

If he/she send an `another.png` or `another.webp`, `fileBox.toFile()` will turn them all into `message-xxxx.jpg`. But if I define the file name, I do not know the picture's format.This is what bothers me. After all, I receive pictures through wechat, not a web page.

I hope my statement will not trouble you. Thank you for your reply.:tada::tada::tada:

**Comment by huan** [comment]
Thank you very much for your explanation, it's very clear now.

According to the below code:

https://github.com/huan/file-box/blob/b345a2210a09f55073edea5194210cf6d1814535/src/file-box.ts#L899-L908

You can see that the FileBox will use `this.name` if there's no parameter passed in for the enforced file name.

When the Wechaty received a FileBox, like `message.toFileBox()`, the `this.name` of the FileBox is deserialized from the data passed from the server.

So your problem is dependent on the Wechaty Puppet Provider implementation: if the `fileBox.toFile()` save the file as name `message-xxx.jpg`, then it means that the server had set the `flieBox.name` to `message-xxx.jpg`.

Please check the source code of the Wechaty Puppet Provider that you are using to confirm it, or contact your Wechaty Puppet Service Provider to fix it.

**Comment by yzh1255245824** [comment]
> Thank you very much for your explanation, it's very clear now.
> 
> According to the below code:
> 
> https://github.com/huan/file-box/blob/b345a2210a09f55073edea5194210cf6d1814535/src/file-box.ts#L899-L908
> 
> You can see that the FileBox will use `this.name` if there's no parameter passed in for the enforced file name.
> 
> When the Wechaty received a FileBox, like `message.toFileBox()`, the `this.name` of the FileBox is deserialized from the data passed from the server.
> 
> So your problem is dependent on the Wechaty Puppet Provider implementation: if the `fileBox.toFile()` save the file as name `message-xxx.jpg`, then it means that the server had set the `flieBox.name` to `message-xxx.jpg`.
> 
> Please check the source code of the Wechaty Puppet Provider that you are using to confirm it, or contact your Wechaty Puppet Service Provider to fix it.

I see! Looks like I have to ask the handsome 好大 hhhhh. Thank you for your help!

**Comment by huan** [comment]
Yes, that's definitely correct, and you are welcome!

**Comment by huan** [comment]
Yes, that's definitely correct, and you are welcome!
