### ISSUE TITLE
[Feature Request] Please provide some function to get `remoteUrl` property

### ISSUE THREAD

**Issue by solarhell** [huan/file-box#9]
It's an issue when using with `wechaty`.(I'm using `wechaty-puppet-puppeteer`)
When i want to parse a message like this
![image](https://user-images.githubusercontent.com/10279583/50722537-cccfe580-110b-11e9-9c21-763b9e12edf4.png)
This message is judged as `Wechaty.Message.Type.Attachment`. So i can only use `msg.toFileBox()` to get the url of this message. (`msg.text()` only give the priview text of the html)
And we can see `remoteUrl` is `private` in `file-box`. So i want to figure out how to get this property?

**Comment by huan** [comment]
According  to your information, it seems that:

1. FileBox is only designed for files, which the purpose is to manage the file transfer easily.
1. Your message is a UrlLink, not an attachment file.
1. So this message should not use FileBox to extract.

If currently, the Puppet provider encapsulates the UrlLink as an attachment file, it seems that we should fix at the puppet side instead of doing any modification of the FileBox library.

I'd like to suggest you file an issue at wechaty-puppet-puppeteer repository and let's see what's wrong on that side.

**Comment by huan** [comment]
@solarhell Do you still have any questions? If not, could you please close this issue?
